### ISSUE TITLE
Migrate identity management to 2FA / OAUTH

### ISSUE THREAD

**Issue by MooseQuest** [SquadQuest/SquadQuest#107]
Description:

Right now a user must share their phone number which is PII in most cases, but also is hard to update when the user gets a new phone number. Something more unique or secure like OAUTH will help anonymize users on the backend, while allowing them to choose which information they would like to share.

**Comment by MooseQuest** [comment]
A feature of the app requires the user to communicate or "link up" with other people on the app. This is done via the phone number. Need to morph this feature or design a unique way for people to exchange contact information easily.

**Comment by themightychris** [comment]
So there's a bigger philosophical question here. Linking identity intrinsically to cell phone numbers was a deliberate design decision on my part that I'm hesitant to shift on readily until there's a critical mass of real users to give feedback on the idea

SquadQuest is inherently a place of very personal information—where you're going to be at what time and if you're on your way to an event and allow it—your live location.

Making the database not be a treasure trove of phone numbers could be a good thing, maybe we can design a way to do that without compromising functionality if any SMS provider offers a way to tokenize them (but then we're locked in to that provider...).

But on the user front, I don't think it would be a good thing to enable users to be any kind of anonymous given that this is a tool for connecting in-person. Part of the idea was positioning SquadQuest as a layer on top of the circle of people you'd already share your phone number with, rather than a social network where you encounter and get content from randos. Making users be 1:1 with phone numbers that can receive texts also puts some breaks on unsophisticated shitposters.

**Comment by themightychris** [comment]
On the "way for people to exchange contact information easily" there's been a couple ideas floating on that:

- #65 and #66 are the no-brainers—instead of someone needing to sign up on their own first before you can send them a friend request or event invite, enable directly text a friend request or event invite such that the person accepting either through your message seamlessly continues them into your friend request or event invite after they sign up
- Ability to generate a reusable secret link for sending you a friend request or joining your event that you can share directly in other channels and more than one person can use to go through a signup flow and get seamlessly continued

In either case though, phone numbers are visible between double-confirmed friend connections
