### ISSUE TITLE
Validate phone numbers globally (beyond North America)

### ISSUE THREAD

**Issue by IguJl15** [SquadQuest/SquadQuest#111]
I recently found the repository and wanted to try it out, but unfortunately, I couldn't log in because the phone validation failed.

Here are some suggestions I believe would be beneficial:

- Accept more phone formats: my issue :)
- Country Selection: A dropdown to select the country first.
- Phone Number Mask: Include symbols to improve readability of the text field.
- Improve the Login Page Design:
  - As the first page a user sees, it should convey welcoming messages. This could also be achieved with an initial landing page.
  
  Validate phone numbers from all over the world (or at least more than North America)

**Comment by IguJl15** [comment]
I can tackle my own issue since I've handled something similar in a previous project.

Are there any contribution guidelines, or can I simply fork the repository and open a pull request?

What your thoughts about it?

**Comment by themightychris** [comment]
Fixed in #115

**Comment by themightychris** [comment]
Welcome @IguJl15 ! I'm curious how you happened to come across this repo?

**Comment by IguJl15** [comment]
I think it happened when I was looking into some "good-first-issue" list and this repo was listed. I'm taking some time from one of my work projects, so I decided to collaborate on some open source projects.

I hope my contribution helped the project development.

So I'm curious about the project. Can you talk about how did you got this idea and what do you expect the project to perform in the short term?

**Comment by themightychris** [comment]
@IguJl15 there's a bit about my motivations/vision at the top of the README

It's something I've been wanting to build for years. A big motivation was how Facebook Events and Meetup.com have so much potential, I've used both extensively to organize small events, and both have completely stagnated and gotten worse because IMO the owners of the two companies have perverse incentives against helping people connect offline wherever they want. Facebook for example has 80k employees and hasn't touched Events in like 10 years—you still can't even filter events by "in the future" or sort results by "time". They used to have a mobile app called "Local" dedicated to events that had a map and slightly better search features that I used to use a lot to find small events, but they discontinued it. 

My motivation is that we all have lots of "weak" IRL connections and activities we want to do more of, but nothing is helping us do that. There are probably lots of things you want to do outside more often, and lots of friends you don't see often that you'd like to spend more time with who want to do the same things, but the logistics are awful. Like remember the last time you met someone and hit it off and discovered you were both into some of the same things.... you maybe exchanged numbers and vowed to get together and then nothing happened. Or maybe you hit them up once for a thing and they were busy and now you don't want to be the person who keeps hitting them up repeatedly. 

So it's one part helping grease those social interactions by making something a bit more structured and passive while still totally social and ad-hoc, and another part helping with the logistics for those of us who put the energy into rallying our friends to get out and do stuff.

Another motivation for me is proving that we can us technology to build things that work just because they're useful without a pitch deck and an investor who wants to see a path within a couple years to earning their money back.

**Comment by IguJl15** [comment]
That looks awesome. I already had this feeling about how difficult it is to get a bunch of friends to go out. I could say it was intensified by how we started to use Discord for absolutely everything since COVID (tabletop games, casual chat, serious chat, studying together, etc.).

Personally, I do not use any social networks (besides LinkedIn) because of all the issues with fake people, fake photos, fake bodies, etc. More importantly, I've never met anyone "relevant" there. It seems like all the people who count as followers would never count as friends. After some years of using it because everyone else did, I just uninstalled it from my phone.

I'm saying this to let you know that I would love to use Squad Quest to meet some real people. I have a Meetup account that notifies me about some online events I would like to watch (I live in a "not so big" city, so no one would use Meetup). So then, I think I'll spread the Squad Quest word in the next weeks.

---

I understood what you said and agree with your motivations overall. I have some doubts, but as soon as I've formulated them better, I'll ask you.

Now that I understand the project's intentions, I'd love to help with it. I know something about UI/UX and much more about Flutter, and so on.

What do you think about it? I think the project has points for improvement that if corrected could bring more prominence to the project and the cause as a whole.

**Comment by themightychris** [comment]
@IguJl15 I would love to collaborate! I'm a bit rusty with Flutter and you clearly have a tight command of it so I'd very much appreciate your help

Maybe we could set up a call to meet and discuss some potential issues to work on? The international phone number support was a no-brainer, but outside of bug fixes let's make sure we're getting aligned on approaches and designs for new features so we can keep things cohesive and avoid any extra work

You can easily use this link to grab any time that works for you: https://calendly.com/chrisalfano/60min-virtual

**Comment by IguJl15** [comment]
@themightychris 
Scheduled! You can delete the link if you want
